### PR TITLE
Removing line preventing headers output

### PR DESCRIPTION
**Pull request by maciekpaprocki**

### CODE REVIEW

**Review by ecoad — APPROVED** [review]

**Comment by ecoad** [comment]
@leonoragilmour @jonsherrard keep your eye out for this as it can cause errors

**Comment by ecoad** [comment]
Its now in master and tagged 1.0.3:
https://packagist.org/packages/shortlist-digital/year-taxonomy#1.0.3

**Comment by jonsherrard** [comment]
This was a bug in the plugin generator I think:

https://github.com/shortlist-digital/wp-plugin-generator/pull/1/commits/0ca5166e1c36b965eba64a613d080229989e83f2

Fixed by @leonoragilmour

**Comment by leogilmour** [comment]
Oh yep sorry I thought I'd caught them all! Will quickly check brand taxonomy too

(_edited_) Oh aha that's just been fixed! great!

**Pull request merged**
